### ISSUE TITLE
Set numeric values methods don't seam to report range errors 

### ISSUE THREAD

**Issue by ashley-b** [EttusResearch/uhd#143]
I've noticed that if I set the gain or frequency directly from C API or the command line utils (eg uhd_siggen) to a out of bounds value there are no error or warning generated.
From looking into the source code it seams to be silently clipping the value to the range for that given element.
I think this should throw a range exception or at least log a warning.

**Comment by mbr0wn** [comment]
@ashley-b this is by design: For better compatibility between devices, the recommended way is to call the setter, then check the returned value, or read the getter.
We could add more warnings (I think that's not a bad idea), but note that warnings go to the logger subsystem. If you're not staring at your screen, you won't know. Your application needs to handle the frequency coercion.

Note that coercion does not only happen at the boundaries. Some devices can only handle full-dB gain steps, and will coerce to the nearest integer, some devices only accept certain frequencies and will coerce on a grid. The decision when to log an error is thus not quite straightforward. If we throw a warning every time input != output, you'd get a lot of false warnings.
