### ISSUE TITLE
EnvironmentError: IOError: usb rx6 transfer status: LIBUSB_TRANSFER_OVERFLOW

### ISSUE THREAD

**Issue by mdasari823** [EttusResearch/uhd#208]
Every time I cancel my usrp_spectrum_sense.py script using ctrl+c, I get the following error the next time I start the script. Any help?

```
terminate called after throwing an instance of 'uhd::io_error'
  what():  EnvironmentError: IOError: usb rx6 transfer status: LIBUSB_TRANSFER_OVERFLOW
Aborted (core dumped)
```

**Comment by michael-west** [comment]
@mdasari823 That error is indicating that the FPGA tried to load too much data into the DMA FIFO in the Cypress FX3 (USB chip).  We made some recent changes in the newest release of UHD that address related issues.  You did not specify which UHD version you were using.  Have you tried UHD 3.13.0.2?  If the issue is happening with 3.13.0.2, please send instructions on how to reproduce the issue so we can look into it further.  Thank you.

**Comment by mdasari823** [comment]
Thanks michael for the response. My bad, the version that I am using is 3.10.1.0. The tutorial at the below link is not updated with latest version, so it was pointing to older version. I will try with latest version and let you know if the problem still persists. Thank you. 

[wiki](https://kb.ettus.com/Building_and_Installing_the_USRP_Open-Source_Toolchain_(UHD_and_GNU_Radio)_on_Linux)

**Comment by phansel** [comment]
@michael-west I'm having a similar issue with the B200 (over USB3) on UHD_3.14.0.0-110-g6af6ac32:

`Error: EnvironmentError: IOError: usb rx6 transfer status: LIBUSB_TRANSFER_OVERFLOW`

The UHD examples (i.e. the ASCII spectrum demo) and our custom GR flowchart work fine initially and then fail with the above error on the second or third restart of the program. The output buffer in the parent terminal also seems to be affected; input text isn't shown on the screen, and carriage returns shift the prompt left-to-right across the terminal.

This seems to occur with all sample rates and bandwidths tested (1-35 Msps/MHz). Physically power-cycling the device seems to remedy the problem, but this is not an acceptable solution in production due to the reset time required for reloading the FPGA; a soft reset would be better.

**Comment by mdasari823** [comment]
@michael-west Yes, I am also getting that error even if I am using 3.13.0.2

**Comment by michael-west** [comment]
@mdasari823 @phansel Thank you for the information.  I have been able to reproduce the error.  We will investigate.

To work around the issue in the meantime, use the command `utils/b2xx_fx3_utils --reset-device` if you ever have to Ctrl-C your application.

**Comment by mdasari823** [comment]
Thank you Michael for the workaround.

**Comment by phansel** [comment]
@michael-west It appears that I had old (3.13.0.1) versions of libuhd003, uhd-host, and libuhd-dev from aptitude installed in /usr/lib/, whereas the version of UHD I compiled from source went to /usr/local/lib/.

After removing the offending old installation files, I still see the error message if sample rate or bandwidth is greater than 1 MHz/Msps. Whenever it appears, the terminal becomes corrupted in this fashion:

```
...
Error: EnvironmentError: IOError: usb rx6 transfer status: LIBUSB_TRANSFER_OVERFLOW
                                                                                                                                                     user@wor ks tation:/usr/local/lib/uhd$ ^C
                                                user@workstation:/usr/local/lib/uhd$ ^C
                                                                                                                user@workstation:/usr/local/lib/uh d$ 
```
This seems like something that would be caused by improper initialization/closure of the stdout buffer before the input stream is ready, so hopefully it's just a bug in examples/ascii_art_dft.hpp/cpp and not in the actual USB library. For reference, I'm using bash 4.3.48(1)-release (x86_64-pc-linux-gnu).

Also, --reset-device doesn't work until I close the corrupted terminal:

```
user@workstation:/usr/local/lib/uhd/utils$ sudo ./b2xx_fx3_utils --reset-device
Device opened (VID=0xXXXX,PID=0xXXXX)
B2xx detected... Control of B2xx granted...

Exception while resetting FX3: EnvironmentError: IOError: Failed to reset FX3 (-1: LIBUSB_ERROR_CODE -1)

```
After killing the corrupted terminal and re-rerunning --reset-device, 

```
user@workstation:/usr/local/lib/uhd/utils$ sudo ./b2xx_fx3_utils --reset-device
Device opened (VID=0x2500,PID=0x0020)
B2xx detected... Control of B2xx granted...

Loading firmware
[INFO] [UHD] linux; GNU C++ version 5.4.0 20160609; Boost_105800; UHD_3.14.0.0-110-g6af6ac32
[INFO] [B200] Loading firmware image: /usr/local/share/uhd/images/usrp_b200_fw.hex...
Device opened (VID=0xXXXX,PID=0xXXXX)
Firmware loaded
Operation complete!  I did it!  I did it!
```
Demos and other programs then work. However, they will crash on the second or third run if the sample rate or bandwidth is higher than 1 MHz. This happens over USB3 on multiple devices.

It  also seems like the --reset-fpga option is broken:

```
user@workstation:/usr/local/lib/uhd/utils$ sudo ./b2xx_fx3_utils --reset-fpga
Device opened (VID=0x2500,PID=0x0020)
B2xx detected... Control of B2xx granted...

Loading firmware
[INFO] [UHD] linux; GNU C++ version 5.4.0 20160609; Boost_105800; UHD_3.14.0.0-110-g6af6ac32
[INFO] [B200] Loading firmware image: /usr/local/share/uhd/images/usrp_b200_fw.hex...
Device opened (VID=0x2500,PID=0x0020)
Firmware loaded
Exception while resetting FPGA: SystemError: invalid code path
  in virtual void b200_iface_impl::set_fpga_reset_pin(bool)
  at ~/gnuradio/uhd/host/lib/usrp/b200/b200_iface.cpp:260

```
--reset-usb doesn't throw any errors, but it also doesn't seem to do anything.

**Comment by phansel** [comment]
@michael-west Thank you for pointing out the reset utility.

 It appears that I had old (3.13.0.1) versions of libuhd003, uhd-host, and libuhd-dev from aptitude installed in /usr/lib/, whereas the version of UHD I compiled from source went to /usr/local/lib/.

After removing that old installation, I still see the error message if sample rate or bandwidth on any program is greater than 1 MHz/Msps. Whenever it appears, the terminal becomes corrupted in approximately this fashion:

```
...
Error: EnvironmentError: IOError: usb rx6 transfer status: LIBUSB_TRANSFER_OVERFLOW
                                                                         user@wor
kstation:/usr/local/lib/uhd$ ^C 
                               user@workstation:/usr/local/lib/uhd$ ^C
                                                                  user@workstation:/usr/local/lib/uh d$ 
```
This seems like something that would be caused by improper initialization/closure of the stdout buffer before the input stream is ready, so hopefully it's just a bug in examples/ascii_art_dft.hpp/cpp and not in the actual USB library. For reference, I'm using bash 4.3.48(1)-release (x86_64-pc-linux-gnu).

Also, --reset-device doesn't work until I close the corrupted terminal:

```
user@workstation:/usr/local/lib/uhd/utils$ sudo ./b2xx_fx3_utils --reset-device
Device opened (VID=0xXXXX,PID=0xXXXX)
B2xx detected... Control of B2xx granted...

Exception while resetting FX3: EnvironmentError: IOError: Failed to reset FX3 (-1: LIBUSB_ERROR_CODE -1)

```
After killing the corrupted terminal and re-rerunning --reset-device, 

```
user@workstation:/usr/local/lib/uhd/utils$ sudo ./b2xx_fx3_utils --reset-device
Device opened (VID=0xXXXX,PID=0xXXXX)
B2xx detected... Control of B2xx granted...

Loading firmware
[INFO] [UHD] linux; GNU C++ version 5.4.0 20160609; Boost_105800; UHD_3.14.0.0-110-g6af6ac32
[INFO] [B200] Loading firmware image: /usr/local/share/uhd/images/usrp_b200_fw.hex...
Device opened (VID=0xXXXX,PID=0xXXXX)
Firmware loaded
Operation complete!  I did it!  I did it!
```
Demos and other programs then work. However, they will crash on the second or third run if the sample rate or bandwidth is higher than 1 MHz. This happens over USB3 on multiple devices.

It  also seems like the --reset-fpga option is broken:

```
user@workstation:/usr/local/lib/uhd/utils$ sudo ./b2xx_fx3_utils --reset-fpga
Device opened (VID=0xXXXX,PID=0xXXXX)
B2xx detected... Control of B2xx granted...

Loading firmware
[INFO] [UHD] linux; GNU C++ version 5.4.0 20160609; Boost_105800; UHD_3.14.0.0-110-g6af6ac32
[INFO] [B200] Loading firmware image: /usr/local/share/uhd/images/usrp_b200_fw.hex...
Device opened (VID=0xXXXX,PID=0xXXXX)
Firmware loaded
Exception while resetting FPGA: SystemError: invalid code path
  in virtual void b200_iface_impl::set_fpga_reset_pin(bool)
  at ~/gnuradio/uhd/host/lib/usrp/b200/b200_iface.cpp:260

```
--reset-usb doesn't throw any errors, but it also doesn't seem to do anything.

**Comment by michael-west** [comment]
@phansel The terminal corruption issue is a separate issue.  I do not see it when I just run benchmark_rate.  I have yet to try ascii_art_dft, but I suspect the terminal corruption is there.  I am digging at the LIBUSB_TRANSFER_OVERFLOW error now.

The b2xx_fx3_utils utility is admittedly very out of date.  The utility was meant only as a debug tool during early stages of bringing up the devices, but we exposed it because some of the operations it provided were useful (such as providing a soft reset for the device).  The --reset-device option works, but the --reset-fpga does not (I'm not sure if it ever did) and the --reset-usb only works on (I believe) Debian/Ubuntu systems.

**Comment by michael-west** [comment]
We have found and are fixing the issue.  There was a bug in the radio_rst logic in the FPGA.

**Comment by phansel** [comment]
> Gotta love it when you encounter a bug, google for it, and you immediately find the fix ...
> Rebuilt my custom FPGA image with that patch added and this fixed it for me !

What patch?

**Comment by XavierTolza** [comment]
Do you know when this bug was introduced so I could eventually downgrade my install until it's fixed?

**Comment by ktsitseklis** [comment]
Hello guys! Where can i find the patch mentioned above?

**Comment by michael-west** [comment]
The fix is being merged and tested now and should be available soon.

@XavierTolza It is not clear when the issue was introduced.  It was originally reported as an unexpected sid error and looks like it has been around for quite a while.

**Comment by forrestv** [comment]
For anyone curious, I think that this is the FPGA patch that resolved this: https://github.com/EttusResearch/fpga/commit/0ac3353f8e2b8224368d34fd63f547e9a231c38e Presumably there were corresponding software changes as the `COMPAT_MAJOR` register was incremented.
