### ISSUE TITLE
Why don't you use uhd::dict instead of std::map？

### ISSUE THREAD

**Issue by zlinwei** [EttusResearch/uhd#292]
There is a question confused me, could you please help me?
```
std::map => O(logn)
but list => O(n)
```
It seems that std::map is faster?
Thanks so much!

**Comment by michael-west** [comment]
@zlinwei Thank you for the post.  Although it is a valid question, we are closing this because it is not a bug.  The choice to use uhd::dict was made a long time ago and I doubt anyone can give you the answer.  For future support questions, please contact support@ettus.com.  If you have a suggested enhancement, please feel free to make a pull request and it will be considered.
