### ISSUE TITLE
errors during building uhd

### ISSUE THREAD

**Issue by planewave** [EttusResearch/uhd#323]
## Issue Description ##

Hi, when I was building the UHD from source files, I encounter errors and stopped at
`multi_usrp_rfnoc.cpp` file

## Setup Details ##

UHD at the master branch
Ubuntu 16.04
I was following [this](https://files.ettus.com/manual/page_install.html) to build.

## Actual Behaviour ##

`Building CXX object lib/CMakeFiles/uhd.dir/usrp/multi_usrp_rfnoc.cpp.o
In file included from /home/xiao/workarea-uhd/uhd/host/lib/usrp/multi_usrp_rfnoc.cpp:16:0:
/home/xiao/workarea-uhd/uhd/host/include/uhd/utils/graph_utils.hpp:30:75: error: converting to ‘std::tuple<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, boost::optional<long unsigned int> >’ from initializer list would use explicit constructor ‘constexpr std::tuple<_T1, _T2>::tuple(_U1&&, _U2&&) [with _U1 = const std::__cxx11::basic_string<char>&; _U2 = const boost::none_t&; <template-parameter-2-3> = void; _T1 = std::__cxx11::basic_string<char>; _T2 = boost::optional<long unsigned int>]’
     {NODE_ID_SEP, boost::none}, {"Radio", boost::none}, {"NullSrcSink", 0}};
                                                                           ^
/home/xiao/workarea-uhd/uhd/host/include/uhd/utils/graph_utils.hpp:30:75: error: converting to ‘std::tuple<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, boost::optional<long unsigned int> >’ from initializer list would use explicit constructor ‘constexpr std::tuple<_T1, _T2>::tuple(_U1&&, _U2&&) [with _U1 = const char (&)[6]; _U2 = const boost::none_t&; <template-parameter-2-3> = void; _T1 = std::__cxx11::basic_string<char>; _T2 = boost::optional<long unsigned int>]’
/home/xiao/workarea-uhd/uhd/host/include/uhd/utils/graph_utils.hpp:30:75: error: converting to ‘std::tuple<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, boost::optional<long unsigned int> >’ from initializer list would use explicit constructor ‘constexpr std::tuple<_T1, _T2>::tuple(_U1&&, _U2&&) [with _U1 = const char (&)[12]; _U2 = int; <template-parameter-2-3> = void; _T1 = std::__cxx11::basic_string<char>; _T2 = boost::optional<long unsigned int>]’
lib/CMakeFiles/uhd.dir/build.make:1177: recipe for target 'lib/CMakeFiles/uhd.dir/usrp/multi_usrp_rfnoc.cpp.o' failed
make[2]: *** [lib/CMakeFiles/uhd.dir/usrp/multi_usrp_rfnoc.cpp.o] Error 1
CMakeFiles/Makefile2:124: recipe for target 'lib/CMakeFiles/uhd.dir/all' failed
make[1]: *** [lib/CMakeFiles/uhd.dir/all] Error 2
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2
`
## Additional Information ##

I checkout V3.15, 
`git checkout v3.15.0.0`
and it compiled with no problem.

some additional questions
Is there a way to install the binaries with example files and python API? if so, I don't need to compile it.
Also, can python API support python virtual environment? I tried and failed at cmake

**Comment by natetemple** [comment]
hi @planewave

This issue is likely due to using C++11 instead of C++14, which is required for the upcoming UHD 4.0 release, which is currently the head of master on the UHD repo.

I would suggest to stick with the latest stable release, which at this time is UHD 3.15.0.0. 

The manual you liked is also tied to UHD 4.0/master. Here is a link to the 3.15.0.0 manual: https://files.ettus.com/manual_archive/v3.15.0.0/html/

Here is a more detailed app note on installing UHD etc for the 3.x series: https://kb.ettus.com/Building_and_Installing_the_USRP_Open-Source_Toolchain_(UHD_and_GNU_Radio)_on_Linux

I do not believe the binaries are built with python support.

You can however build it into a virtualenv, the instructions should be something along the lines of:

```
mkdir pyuhdtest
cd pyuhdtest
virtualenv -p python3 .
. bin/activate 

mkdir src
cd src
git clone https://github.com/EttusResearch/uhd
git checkout v3.15.0.0
cd uhd/host
mkdir build
cd build
cmake -DENABLE_PYTHON3=ON -DCMAKE_INSTALL_PREFIX=~/pyuhdtest/ ..
make -j
make install # no sudo

~/pyuhdtest/lib/uhd/utils/uhd_images_downloader.py

uhd_usrp_probe
```

Please email support@ettus.com for any follow up questions, as this is not specific to a bug with UHD.
