### ISSUE TITLE
Special characters cause issues in custom block XML blockname

### ISSUE THREAD

**Issue by ctonermw** [EttusResearch/uhd#363]
## Issue Description ##
Block names with special characters in the XML  blockname not displaying correctly

## Setup Details ##
**Using UHD-3.15.LTS with a X310**
1) Create a custom RFNoC block and in the the corresponding block XML set the blockname to something with an underscore, for example:
`<blockname>underscore_issue</blockname>`
2) Create a bitstream with the custom block and deploy it to the device.
3) Ensure the XML is found by correctly setting UHD_RFNOC_DIR
4) Run `uhd_usrp_probe`

## Expected Behavior ##

The custom block should appear at the end of the exectuables output as follows:
```
RFNoC blocks on this device:
*underscore_issue_0
```

## Actual Behaviour ##

The block name does not appear, only the extension to it.
```
RFNoC blocks on this device:
*_0
```

## Additional Information ##

The same is true for other special characters.
Removing special characters from the blockname solves the issue for now

**Comment by mbr0wn** [comment]
@ctonermw Underscores in RFNoC block name are not supported. We weren't able to fix that in UHD 3 (it is fixed in UHD 4) but for now, you'll have to stick to blocks that match this regex: https://github.com/EttusResearch/uhddev/blob/bc585b4368ebdae3887bc1bcf4ba8fd7f52b25f0/host/include/uhd/rfnoc/constants.hpp#L101
