### ISSUE TITLE
UHD 4.0 N320 property tree access causes SIGSEGV

### ISSUE THREAD

**Issue by ccera-astro** [EttusResearch/uhd#385]
From the mailing list:

 But, I got the Segmentation fault at
> usrp->get_device()->get_tree()->access<bool>("mboards/0/dboards/A/tx_frontends/0/los/lo1/lo_distribution/LO_OUT_0/export").set(true);

User with an N320, trying to issue a "set" against the above portion of the property tree--result is a Seg Fault.

Other access of fthe "usrp" object like "set_gain", etc, work flawelessy, so this looks like it's internal to UHD.

I don't have an N320 to test.

**Comment by michael-west** [comment]
@ccera-astro We have a template for issues in order to get the required information to properly investigate an issue.

From the brief information provided, it seems like you are trying to export an LO on an N320.  The N320 cannot export an LO.  It can only import one.  The N321 is required to export an LO.

If this does not resolve the issue, please open a new issue and provide more detailed information.
