### ISSUE TITLE
why is there no master cmakelist.txt ?

### ISSUE THREAD

**Issue by nielsvanetten** [EttusResearch/uhd#432]

**Comment by brentstapleton** [comment]
Hi @nielsvanetten, there are many CMakeLists.txt files in uhd. Please take a look at the [README.md](https://github.com/EttusResearch/uhd/blob/master/README.md), which in turn links to the [instructions to build from source](https://files.ettus.com/manual/page_build_guide.html).

I think what you're asking for here is the CMakeLists.txt to build the UHD host applications and library, which can be [found here](https://github.com/EttusResearch/uhd/blob/master/host/CMakeLists.txt). Hope this helps. Otherwise, please add more details for what you're looking for.

**Comment by mbr0wn** [comment]
Thanks @brentstapleton! @nielsvanetten, I hope this clears things up for you.
