### ISSUE TITLE
uhd_usrp_probe : failure : CODEC loopback test failed

### ISSUE THREAD

**Issue by pfeatherstone** [EttusResearch/uhd#471]
## Issue Description ##
When running ```uhd_usrp_probe```, i get error:
```
[WARNING] [0/Radio_0] CODEC loopback test failed! Expected: 0x68D08E10 Received (TX/RX): 0x68D08E10/0x2C48E00
```

## Setup Details ##
* I have an E320
* I've installed UHD v3.14.1.1
* I've gone through the setup guide
* ```uhd_find_devices``` is correctly showing my device

**Comment by pfeatherstone** [comment]
I know this isn't really a libuhd issue, but i can't find **any** information on what could be causing this error. Any help would be great.

**Comment by pfeatherstone** [comment]
I think this type of error occurs if you so much as breath incorrectly on the SDR. The fix seems to be to reinstall the firmware and reboot and make sure every time you use the library, either directly or indirectly (GNU radio) clean up your resources. Killing the GNU radio script abruptly seemed to cause this.

**Comment by michaelld** [comment]
@pfeatherstone it could very well be that UHD 3.14.1.1 has issues with respect to the E320; that release is pretty old. Since you can update the filesystem via an SDcard swap, if you could test out on UHD 3.15 at oldest, or, preferably, the current release (4.1.0.1), those would provide more useful information to help you out here. UHD 4, in particular, provides many bug fixes across the board for UHD-based SDRs, and it is what we recommend for all users who can update to it.

**Comment by pfeatherstone** [comment]
Oh ok thank you. I thought i read in the [docs](https://kb.ettus.com/E320_Getting_Started_Guide#Install_and_Setup_the_Software_Tools_on_Your_Host_Computer) that release 3.14 was preferred.

**Comment by michaelld** [comment]
OK . Here's the language I see (quoted verbatim) ... I would read the below, since it is stated multiple times, to use the latest stable version of UHD and the filesystem. That at the time this AppNote was written, this was 3.14 ... and clearly this AppNote is kinda old since the current stable version is 4.1.0.1. I will rephrase this information slightly to hopefully make it more clear what we mean, but I do hope my note here helps clarify the information.
```
It is strongly​ recommended to use the latest stable version of UHD. It is generally recommended to use the maintenance branch of the latest stable version, for example UHD-3.14.

To find the latest release of UHD, see the UHD repository at https://github.com/ettusresearch/uhd .

The USRP E320 requires UHD version 3.13.0.2 or later. It is recommended to use the UHD-3.14 maintenance branch at the time of this writing.

NOTE: Before operating the device, it is​ ​strongly​ recommended to update to the latest version of the Embedded Linux file system on the SD card.
```

**Comment by pfeatherstone** [comment]
Okidok. I will update to 4.1.0.1. Cheers

**Comment by pfeatherstone** [comment]
@michaelld I'm getting a couple issues with 4.1.0.1.
If i build and install using ```ninja```, libuhd.so doesn't get installed, though it does get built. If i build and install using ```make```, libuhd.so does get installed but none of the include headers get installed. Is 4.1.0.1 really a stable release?

**Comment by pfeatherstone** [comment]
In fact, no matter what i do, the headers don't get installed.

**Comment by michaelld** [comment]
@pfeatherstone hmmm ... that's odd ... I've installed 4.1.0.1 (the release) on various OSs with success. What OS are you using for this? Also: can you try the basic CMake / make from a clean build directory & UHD release?

**Comment by pfeatherstone** [comment]
Yep will do that tomorrow. I'm building on Ubuntu18 using cmake 3.20. Note that UHD 3.14 works fine.

**Comment by pfeatherstone** [comment]
@michaelld Ok i did a clean build of 4.1.0.1 and it seemed to install correctly. I have no idea what happened the first few times round. I'm gonna put it down to a mistake I made due to lack of coffee.

I have noticed though (this may be a tangent but sod it) v4.1.0.1 seems to be using C++11 onward since ```uhd::usrp::multi_usrp::sptr``` is now a ```std::shared_ptr``` not ```boost::shared_ptr```, yet libuhd is still using boost_thread. Why is that? If you're using C++11, you can use the thread utilities in the standard library... Do you have plans to phase out boost if you're adopting later C++ standards? If you were to use c++17, you could drop boost_filesystem and probably boost_system too. Depending on how you're using chrono, you could drop boost_date_time if ```std::chrono``` is sufficient. boost_serialization could be replaced with a simple header-only variant like [yas](https://github.com/niXman/yas), [cereal](https://github.com/USCiLab/cereal), or [json](https://github.com/nlohmann/json) (which supports msgpack). libuhd would become pretty self-contained then... I would be interested in reading your comments, i'm a big fan of removing runtime dependencies.

**Comment by mbr0wn** [comment]
Yes, we are planning to phase out Boost where possible. We've removed a whole bunch of Boost in the recent past, but there are often subtle side-effect, especially with threading. We definitely want to move to `std::chrono`, because that covers a lot of the Boost versions.

There's some Boost bits we can' easily replace (asio, for example). But boost_thread is replacable, and it's happening. It's just pretty ingrained into UHD for a long time now, and removing it is time-consuming. But it's happening!

Thanks for all the feedback. Did your codec loopback error go away with the update?

**Comment by mbr0wn** [comment]
Oh, and we'll eventually switch to C++17. We don't like requiring all our users to use super new compilers, though, so we usually give it a few years. For example, we have a lot of CentOS users who have a hard time with modern compilers.

**Comment by pfeatherstone** [comment]
Sorry I didn't close this earlier. The loop back error vanished with the update. Thanks. And yey for removing boost.

**Comment by pfeatherstone** [comment]
So i'm getting this issue now when updating to latest release: https://github.com/EttusResearch/uhd/issues/534
My fix is to rollback to v3.14.1.1.
What could be causing this error?

**Comment by mbr0wn** [comment]
@pfeatherstone Are you getting the CODEC loopback error, or the lo_locked error? If it's the latter, then let's keep this closed and move the discussion to the other issue.

**Comment by pfeatherstone** [comment]
I get the "lo_locked" error when using v4.1 and and get the "CODEC loopback error" (occasionally) when using v3.14

**Comment by mbr0wn** [comment]
OK, but in that case, I'll close this (and we can discuss the lo_locked issue on the other PR) since we won't be fixing UHD 3.14 any more.

**Comment by pfeatherstone** [comment]
Fair enough

**Comment by pfeatherstone** [comment]
@mbr0wn do you know what could be causing `CODEC loopback test failed! Expected: 0x68D08E10 Received (TX/RX): 0x68D08E10/0x2C48E00`

I know you said that version 3 wouldn't be fixed, but when using version 4, streaming samples just hangs. The odd thing is that it only ever happens on one of the two E320 I have. For the dodgy one, I have to continuously run `uhd_image_loader` until it stops throwing that error. I don't understand why it only happens on one of the SDRs. Both have the same version, 3.15.

**Comment by pfeatherstone** [comment]
I'm still getting this behaviour. It breaks with 3.14 and hangs with 3.15, 4.1, 4.2 and 4.3. Is there a way to get more verbosity in the logging?
