### ISSUE TITLE
Possible Error in Index Variable Comparison

### ISSUE THREAD

**Issue by johnwstanford** [EttusResearch/uhd#485]
Should this be `ptr * sizeof(uint64_t) <= max_size_bytes`?  You're using `ptr` to index a `uint64_t*`, which is 8 bytes each, but the variable name you're comparing it to says bytes.  

https://github.com/EttusResearch/uhd/blob/919043f305efdd29fbdf586e9cde95d9507150e8/host/lib/rfnoc/chdr_types.cpp#L143

**Comment by manderseck** [comment]
@johnwstanford Thanks for reporting this issue. The variable name `max_size_bytes` implies that the assertion compares with the maximum number of bytes. When checking the header file this variable is called `num_elems`. Then the assertion makes sense as it is. 
Since the variable name is misleading indeed I'll create a pull request to change it according to the header file. The issue will close automatically when this will have been merged internally, then afterwards it'll still take a few days until it is merged into the public repo.
