### ISSUE TITLE
Big bug of UHD for new revision Ettus USRP B200/210 issued after 2015

### ISSUE THREAD

**Issue by btrsdr** [EttusResearch/uhd#78]
I tried to install various Linux forks and all of them  used UHD 3.0.7 from repositories.

Some interesting. Device detected by linux OS and  worked all sdr's programs.
There are no errors! Choosing RX / TX or RX2 nothing changes. RF gain is adjusted, but there is no change. The sound is noise, but no radio can not hear. Waterfall shows noise. TX button works, but the transmitter does not transmit.

I have resolved it problem. It turns out, the new (green) cards Ettus B200/210 does not work correctly with the drivers that come with the Debian's repository. The repository has the old driver 003.007. When I put UHD from source code, installed last v. 003.010, the program began to work successfully! I just started other programs - gqrx, and etc.

But that is not all. Debian 8.0.6 still has in its repository outside the old driver for the new card - 3.0.7. In addition, debian 8.0.6 as opposed to 8.0.0 does not see the device. When  try to run uhd_find_devices
Can see:
linux; GNU C ++ version 4.9.2; Boost_105500; UHD_003.009.005-0-g32951af2
No UHD Devices Found

messages log:

[ 2514.168911] usb 2-1.6: new high-speed USB device number 4 using ehci-pci
[ 2514.261751] usb 2-1.6: New USB device found, idVendor=2500, idProduct=0020
[ 2514.261757] usb 2-1.6: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[ 2514.261760] usb 2-1.6: Product: WestBridge 
[ 2514.261762] usb 2-1.6: Manufacturer: Cypress
[ 2514.261765] usb 2-1.6: SerialNumber: 0000000004BE
[ 4419.164123] usb 2-1.6: USB disconnect, device number 4
[ 4420.641402] usb 2-1.2: new high-speed USB device number 5 using ehci-pci
[ 4420.734450] usb 2-1.2: New USB device found, idVendor=2500, idProduct=0020
[ 4420.734456] usb 2-1.2: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[ 4420.734459] usb 2-1.2: Product: WestBridge 
[ 4420.734462] usb 2-1.2: Manufacturer: Cypress
[ 4420.734465] usb 2-1.2: SerialNumber: 0000000004BE

I tried last UHD from  sources:
git clone git://github.com/EttusResearch/uhd.git 
etc...
But result - device not found.
 
PS. My USRP B200 properly and running under windows 7.

**Comment by mbr0wn** [comment]
@btrsdr Thanks for reporting. Unfortunately, if there's an issue exclusively with old versions of UHD, we can't fix anything. Distros such as Debian will slowly update their versions over time, and then the fixes will be available. Until then, only a manual installation (e.g. from source) will help.

FYI, B2xx support was added with UHD 3.6.0, and mostly finalized with 3.6.2. There were a lot of fixes in the meantime, though.

I'm a bit surprised about your UHD 3.9.5 not detecting a USRP. This might also be a system configuration if it works on a different system.

Overall, there's not much we can do here -- but maybe we can help you otherwise. In that case, please contact the usrp-users mailing list.
