### ISSUE TITLE
race condition when launching 2 flowgraphs with b200s at the same time

### ISSUE THREAD

**Issue by osh** [EttusResearch/uhd#94]
File ".........../lib/python2.7/dist-packages/gnuradio/uhd/uhd_swig.py", line 2078, in make
    return _uhd_swig.usrp_sink_make(*args)
RuntimeError: AssertionError: libusb_claim_interface(this->get(), interface) == 0
  in virtual void libusb_device_handle_impl::claim_interface(int)
  at /....../src/uhd/host/lib/transport/libusb1_base.cpp:271

each flowgraph is a seperate GNU Radio process running with user level permissions
uhd host version is f9ef7bda990591962a740aa3ab249aee30451ed9

device args in this case specifies the serial number for each usrp

**Comment by mbr0wn** [comment]
This is a legitimate issue, and we're looking into it.

**Comment by osh** [comment]
It's actually quite an important use case, usually when I want my flowgraph samples synchronized to with 1ns I launch the two gr apps within 0.5ns of each other.

**Comment by deanhuff** [comment]
it appears this race still exists as of 3.14 any updates?

**Comment by manderseck** [comment]
@osh @deanhuff This issue seems to have been around for way too long. Therefore I checked if it still exists with the latest code from Git. Tests performed:
1. One instance of GNU Radio Companion with a flowgraph consisting of two USRP sources and two QT GUI Waterfall sinks in parallel for two USRPs B210. Works.
2. One instance of GRC with two different flowgraphs both consisting of a USRP source and a QT GUI Waterfall sink for two USRPs B210. Works.
3. Two instances of GRC with a flowgraph each consisting of a USRP source and a QT GUI Waterfall sink, again for two USRPs B210. Works, too.

Therefore I consider this issue as gone with the latest version. I'm really sorry that this issue was not handled earlier. Please re-open if you still encounter this issue with the latest UHD versions.
